# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
baseUrl = "http://codysheridan.com/"

[_.globalMeta]
title = "Cody Sheridan"
description = "Manufacturing Mindset. Modern Software Craftsmanship."
longDescription = "Cody Sheridan is a software developer who brings a manufacturing mindset to modern software craftsmanship. Discover projectd and professional experience."
cardImage = "https://codysheridan.com/sheridan-meta.webp"
keywords = ["web development", "design", "technology"]

[_.aboutMeta] 
title = "About Cody Sheridan" 
description = "Developer. Builder. Relentless problem-solver." 
longDescription = "Learn more about Cody Sheridan — a developer who applies a manufacturing mindset to modern software craftsmanship. Explore his professional background, technical experience, and the principles that guide his work."
cardImage = "https://codysheridan.com/sheridan-meta.webp"
keywords = ["resume", "software developer", "engineering mindset", "craftsmanship", "technology"] 

[_.projectMeta] 
title = "Projects by Cody Sheridan" 
description = "A showcase of practical software craftsmanship — built with grit and precision." 
longDescription = "Explore Cody Sheridan’s portfolio of projects — built on craftsmanship, curiosity, and a dedication to building things that work. Includes links to live apps and GitHub repositories."
cardImage = "https://codysheridan.com/sheridan-meta.webp"
keywords = ["portfolio", "projects", "software craftsmanship", "frontend", "full stack"]

[_.notFoundMeta]
title = "Cody Sheridan 404"
description = "Looks like this page went off the rails."
longDescription = "The page you are looking for does not exist. Maybe it never existed. Spooky."
cardImage = "https://codysheridan.com/sheridan-meta.webp"

[_.hero]
title = "Cody Sheridan"
subtitle = "Manufacturing Mindset. Modern Software Craftsmanship."
image = "https://codysheridan.com/headshot-close.webp"

ctaText = "View Projects"
ctaUrl = "/projects"

[_.personal]
name = "Cody Sheridan"
technologies = ["csharp", "java", "python", "javascript", "typescript", "react", "angular", "sql", "supabase", "linux", "powershell"]

[_.personal.email]
text = "cody.sheridan@pm.me"
url = "mailto:cody.sheridan@pm.me"

[_.personal.location]
text = "United States"
# url intentionally omitted

[_.personal.githubProfile]
text = "GitHub"
url = "https://github.com/kuhlekt1v"

[_.personal.linkedinProfile]
text = "LinkedIn"
url = "https://www.linkedin.com/in/codysheridan/"

[_.personal.portfolio]
text = ""
url = "https://github.com/kuhlekt1v/portfolio"

[_.texts]
aboutName= "About Me"
projectsName = "Projects"
viewAll = "View All"
noArticles = "Articles coming soon!"
noProjects = "Projects coming soon!"

[_.menu]
home = "/"
projects = "/projects"
about = "/about"
