# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
baseUrl = "http://localhost:4321/"

[_.globalMeta]
title = "Cody Sheridan"
description = "Manufacturing Mindset. Modern Software Craftsmanship."
longDescription = "Cody Sheridan is a software developer who brings a manufacturing mindset to modern software craftsmanship. Discover projectd and professional experience."
cardImage = "https://zaggonaut.dev/michael-michael-dam-unsplash.webpdam-unsplash.webp"
keywords = ["web development", "design", "technology"]

[_.blogMeta]
title = "Zaggonaut Blog"
description = "Practical wisdom, unfiltered thoughts, and hot takes."
longDescription = "Web development, tech trends, and the occasional programming mishap."
cardImage = "https://zaggonaut.dev/michael-dam-unsplash.webp"
keywords = ["web development", "design", "technology"]

[_.projectMeta]
title = "Zaggonaut Projects"
description = "A list of my web development projects and developer tools."
longDescription = "All of my projects, including both frontend and full-stack applications."
cardImage = "https://zaggonaut.dev/michael-dam-unsplash.webp"
keywords = ["web development", "design", "technology"]

[_.notFoundMeta]
title = "Zaggonaut 404"
description = "The page you are looking for does not exist."
longDescription = "The page you are looking for does not exist. Maybe it never existed. Spooky."
cardImage = "https://zaggonaut.dev/michael-dam-unsplash.webp"

[_.hero]
title = "Cody Sheridan"
subtitle = "Manufacturing Mindset. Modern Software Craftsmanship."
image = "http://localhost:4321/headshot-close.jpg"
ctaText = "View Projects"
ctaUrl = "/projects"

[_.personal]
name = "Cody Sheridan"

[_.personal.email]
text = "cody.sheridan@pm.me"
url = "mailto:cody.sheridan@pm.me"

[_.personal.location]
text = "United States"
# url intentionally omitted

[_.personal.githubProfile]
text = "GitHub"
url = "https://github.com/kuhlekt1v"

[_.personal.linkedinProfile]
text = "LinkedIn"
url = "https://www.linkedin.com/in/codysheridan/"

[_.personal.portfolio]
text = ""
url = "https://github.com/kuhlekt1v/portfolio"

[_.texts]
articlesName = "Articles"
projectsName = "Projects"
viewAll = "View All"
noArticles = "No articles found."
noProjects = "No projects found."

[_.menu]
home = "/"
projects = "/projects"
about = "/about"
