about = "Hey! I'm Cody—a senior full stack developer with 5+ years building scalable Azure applications and 8 years in manufacturing. I love bridging business and tech teams, turning complex requirements into real solutions, and leading projects that streamline workflows, cut costs, and boost quality." 
[[_.experience]]
company = "Pratt & Whitney"
title = "Lead Developer"
date = "January 2025 - Present"
location = "Connecticut/Remote"
details = [
"Supported the Solumina Manufacturing Execution System (MES), standardizing workfl ows and documentation through the MES Center of Excellence.",
"Built and maintained Python-based ETL pipelines for RCVS dashboards, enabling senior leadership to track material fl ow from forging to machining.",
"Co-led the MES 2.0 DevOps process mapping initiative earning CORE Champion certifi cation and delivering Agile documentation, role matrices, and cross-team workflows.",
"Improved CI/CD and Agile adoption for the Solumina G8 platform, designing automated deployment processes with GitHub and Jira.", 
"Maintained and expanded MES onboarding experience with SDK setup guides, CI/CD templates, and best practices documentation.",
"Supported the OACIS public-facing landing page with ReactJS, mentoring junior developers through code reviews and pair programming."
]

[[_.experience]]
company = "Pratt & Whitney"
title = "Senior Software Developer"
date = "November 2023 - January 2025"
location = "Connecticut/Remote"
details = [
"Core developer for an enterprise application serving 5,000+ global users built with Angular, C#, SharePoint, AgilePoint, and SQL.",
"Upgraded Angular Core/Material from v10 → v15, resolving compatibility issues and improving stability.",
"Agile champion for team, achieving Agile Champion Certifi cation and completing Scrum@Scale training.",
"Mentored and reviewed code for two offshore junior developers."
]

[[_.experience]]
company = "Pratt & Whitney"
title = "Manufacturing IT Systems Manager"
date = "November 2021 - November 2023"
location = "Connecticut/Remote"
details = [
    "Core member of the OACIS team, improving manufacturing effciency with real-time analytics and Azure cloud technologies.",
    "Developed a .NET Core + React interface to capture critical metadata, closing gaps in the OACIS pipeline.",
    "Engineered Python ETL solutions for raw machine data, optimizing formats for OLAP and cloud storage.",
    "Achieved measurable results: reduced machining cycle time by 4.4 hours per part across 43 machines driving $574K annual savings."
]

[[_.experience]]
company = "Toolio Rentals"
title = "Full Stack Developer (Freelance)"
date = "June 2024 - April 2025"
location = "Connecticut/Remote"
details = [
"Architected and delivered a cross-platform rental order app (iOS, Android, Web) with Angular Ionic and Supabase.",
"Integrated Stripe checkout (Apple Pay, Google Pay) for seamless multi-platform payments.",
"Deployed via Netlify with GitHub Actions CI/CD; managed DevOps as sole developer."
]

[[_.experience]]
company = "Lee Company"
title = "Programmer"
date = "January 2019 - November 2021"
location = "Westbrook, CT"
details = [
"Developed a parts tracking application using .NET MVC, JavaScript, SQL, and Bootstrap, eliminating manual data entry and enhancing operational efficiency.",
"Streamlined data man5agement processes via automated PowerShell scripts.", 
"Automated reporting with PowerShell, SQL, and Batch scripting for CPK quality control and ISO 9000 compliance."
]

[[_.education]]
institution = "Fairfield University"
degree = "M.S. Management of Technology"
graduation = "2022 (Summa Cum Laude)"
location = "Fairfield, CT"
honors = "Tau Beta Phi Engineering Honor Society, Alpha  Sigma Nu Jesuit Honor Society"
coursework = "Software Design, Information Systems, Information Security, Global Competitive Strategy, Strategic Management of Technology & Innovation"
[[_.education]]
institution = "Temple University"
degree = "B. Architecture"
graduation = "2014"
location = "Philadelphia, PA"
honors = ""
coursework = "Calculus, Structural Analysis, Architectural Design, History of Architecture"

[[_.certification]]
title = "Registered Scrum Master"
affiliation = "Scrum Inc."
date = "September 2022"
[[_.certification]]
title = "Gregor Ojstersek Senior Engineer Lead Cohort"
affiliation = "Maven"
date = "June 2025"
[[_.certification]]
title = "Leadership Mastermind Program"
affiliation = "RIT Executive Education"
date = "October 2025"
[[_.certification]]
title = "Microsoft Certified: Azure Fundamentals"
affiliation = "Microsoft"
date = "May 2024"
[[_.certification]]
title = "AWS Certified Cloud Practitioner"
affiliation = "Amazon Web Services"
date = "December 2022"

[_.skills]
languages = ["C#", "Python", "JavaScript/TypeScript", "Java", "SQL", "HTML/CSS", "PowerShell", "Bash"]
tools = ["Supabase", "Azure", "Git/GitHub", "Postman", "Netlify", "Linux", "PowerShell", "Jira", "Confluence", "Figma"]
practices = ["Agile/Scrum", "CI/CD", "ETL", "Cloud-Native apps", "Cross-Platform development", "Mentorship"]
